### ISSUE TITLE
Overwriting Access Keys

### ISSUE THREAD

**Issue by telezoic** [harvard-lil/thread-keeper#14]
Hi There, 

I'm testing the app locally using the osx instructions. and I have noticed that when I generate an access token:

```
$ uuidgen
BB67BBC4-1F4B-4353-8E6D-9927A10F4509 
```

and add it to the access-keys.json file:

```
{
  "BB67BBC4-1F4B-4353-8E6D-9927A10F4509": true,
}
```

starting the app overwrites the file and removes the token

```
{}

```
and at localhost:3000 I get an error when I insert my key: 
<img width="1271" alt="Screen Shot 2022-11-28 at 09 33 56" src="https://user-images.githubusercontent.com/444648/204343451-ba54ddb2-668b-4944-9043-b10e527a006c.png">

if i tighten up the perms on the file to try and stop the overwrite the app fails to start: 

```
Error: EACCES: permission denied, open '/Users/Daniel/Desktop/eSabretache/thread-keeper/app/data/access-keys.json'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at new AccessKeys (file:///Users/Daniel/Desktop/eSabretache/thread-keeper/app/utils/AccessKeys.js:47:10)
    at file:///Users/Daniel/Desktop/eSabretache/thread-keeper/app/server.js:27:20
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async requireServerPluginFromPath (/Users/Daniel/Desktop/eSabretache/thread-keeper/node_modules/fastify-cli/util.js:74:22)
    at async runFastify (/Users/Daniel/Desktop/eSabretache/thread-keeper/node_modules/fastify-cli/start.js:85:12)
    at async main (/Users/Daniel/Desktop/eSabretache/thread-keeper/node_modules/fastify-cli/lib/watch/fork.js:40:13) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/Users/Daniel/Desktop/eSabretache/thread-keeper/app/data/access-keys.json'
  ```
  
  Do you have any advice you could share to help me troubleshoot this? 
  
  Thanks, 
  Dan

**Comment by matteocargnelutti** [comment]
Hi Dan,

I think a typo in `README.md` led to this issue:
```json
{
  "BB67BBC4-1F4B-4353-8E6D-9927A10F4509": true,
}
```

The snippet above is not valid JSON because of the trailing coma after `true`.
This is most likely the reason why `thread-keeper` fails to parse it and overrides it.

The following `access-keys.json` should work:
```json
{
  "BB67BBC4-1F4B-4353-8E6D-9927A10F4509": true
}
```

Please let us know if that solved your problem.

I'll fix the README 😄 .

Best,

**Comment by telezoic** [comment]
Thanks @matteocargnelutti , 
The overwriting is corrected, but the process fails to create a capture:
```
{"level":30,"time":1669664420684,"pid":97944,"hostname":"eSabretache3","reqId":"req-6","msg":"Capture capacity: 0 / 200."}
^@{"level":50,"time":1669664456636,"pid":97944,"hostname":"eSabretache3","reqId":"req-6","msg":"Capture failed. TypeError: parsedUrl.pathnameparsedUrl.search.replaceAll is not a function"}
{"level":30,"time":1669664456641,"pid":97944,"hostname":"eSabretache3","reqId":"req-6","res":{"statusCode":500},"responseTime":35957.24971818924,"msg":"request completed"}
{"level":30,"time":1669664456648,"pid":97944,"hostname":"eSabretache3","reqId":"req-7","req":{"method":"GET","url":"/static/index.css","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":63630},"msg":"incoming request"}
{"level":30,"time":1669664456652,"pid":97944,"hostname":"eSabretache3","reqId":"req-7","res":{"statusCode":304},"responseTime":4.572414875030518,"msg":"request completed"}
{"level":30,"time":1669664456653,"pid":97944,"hostname":"eSabretache3","reqId":"req-8","req":{"method":"GET","url":"/static/index.js","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":63641},"msg":"incoming request"}
{"level":30,"time":1669664456653,"pid":97944,"hostname":"eSabretache3","reqId":"req-9","req":{"method":"GET","url":"/static/ocean-of-books.svg","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":63642},"msg":"incoming request"}
{"level":30,"time":1669664456653,"pid":97944,"hostname":"eSabretache3","reqId":"req-a","req":{"method":"GET","url":"/static/lil.svg","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":63643},"msg":"incoming request"}
{"level":30,"time":1669664456654,"pid":97944,"hostname":"eSabretache3","reqId":"req-8","res":{"statusCode":304},"responseTime":1.168097972869873,"msg":"request completed"}
{"level":30,"time":1669664456654,"pid":97944,"hostname":"eSabretache3","reqId":"req-9","res":{"statusCode":304},"responseTime":1.0990338325500488,"msg":"request completed"}
{"level":30,"time":1669664456654,"pid":97944,"hostname":"eSabretache3","reqId":"req-a","res":{"statusCode":304},"responseTime":1.0673580169677734,"msg":"request completed"}

```

Thanks, 

D.

**Comment by matteocargnelutti** [comment]
@telezoic I'm glad this worked! 
Hmmm, based on these logs, I think you might run a version of Node.js that doesn't support [String.prototype.replaceAll()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#browser_compatibility). 
Would you mind checking what version of Node JS you're using, and if it's less than 18, upgrading?

Cheers.

**Comment by telezoic** [comment]
Thanks @matteocargnelutti 

I upped it to 19. 

but now my page crashes when I try and capture

```
rt":64103},"msg":"incoming request"}
{"level":30,"time":1669666491405,"pid":99170,"hostname":"eSabretache3","reqId":"req-1","res":{"statusCode":200},"responseTime":18.87699794769287,"msg":"request completed"}
{"level":30,"time":1669666491451,"pid":99170,"hostname":"eSabretache3","reqId":"req-2","req":{"method":"GET","url":"/static/index.css","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":64103},"msg":"incoming request"}
{"level":30,"time":1669666491455,"pid":99170,"hostname":"eSabretache3","reqId":"req-2","res":{"statusCode":304},"responseTime":4.1871678829193115,"msg":"request completed"}
{"level":30,"time":1669666491457,"pid":99170,"hostname":"eSabretache3","reqId":"req-3","req":{"method":"GET","url":"/static/index.js","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":64104},"msg":"incoming request"}
{"level":30,"time":1669666491457,"pid":99170,"hostname":"eSabretache3","reqId":"req-4","req":{"method":"GET","url":"/static/ocean-of-books.svg","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":64105},"msg":"incoming request"}
{"level":30,"time":1669666491458,"pid":99170,"hostname":"eSabretache3","reqId":"req-3","res":{"statusCode":304},"responseTime":1.1486098766326904,"msg":"request completed"}
{"level":30,"time":1669666491459,"pid":99170,"hostname":"eSabretache3","reqId":"req-4","res":{"statusCode":304},"responseTime":1.2405059337615967,"msg":"request completed"}
{"level":30,"time":1669666491459,"pid":99170,"hostname":"eSabretache3","reqId":"req-5","req":{"method":"GET","url":"/static/lil.svg","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":64106},"msg":"incoming request"}
{"level":30,"time":1669666491460,"pid":99170,"hostname":"eSabretache3","reqId":"req-5","res":{"statusCode":304},"responseTime":0.5049741268157959,"msg":"request completed"}
{"level":30,"time":1669666518964,"pid":99170,"hostname":"eSabretache3","reqId":"req-6","req":{"method":"POST","url":"/","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":64103},"msg":"incoming request"}
{"level":30,"time":1669666518965,"pid":99170,"hostname":"eSabretache3","reqId":"req-6","msg":"Capture capacity: 0 / 200."}
^@{"level":30,"time":1669666540956,"pid":99858,"hostname":"eSabretache3","msg":"Server listening at http://[::1]:3000"}
{"level":30,"time":1669666540958,"pid":99858,"hostname":"eSabretache3","msg":"Server listening at http://127.0.0.1:3000"}
^@^@^@
```
<img width="1216" alt="Screen Shot 2022-11-28 at 12 17 18" src="https://user-images.githubusercontent.com/444648/204372783-851c2bc4-f559-4adb-be55-df5642706abb.png">

Do you have any suggestions :) 



Thanks, 

D.

**Comment by matteocargnelutti** [comment]
@telezoic Hmm I am not too sure, I can't reproduce this issue locally. 
Just in case, a classic: Have you tried removing the project's `node_modules` and re-installing dependencies after upgrading to Node 19?

**Comment by telezoic** [comment]
Thanks @matteocargnelutti, 

I switched gears, pulled your recent changes, and put this on an ubuntu (22.10) server and it's running without error here :) 

Thanks again, 

D.

**Comment by matteocargnelutti** [comment]
Awesome 😄 !

**Comment by telezoic** [comment]
Thanks again @matteocargnelutti. We're now using this awesome tool in conjunction with tweet URLs (built from Twitter's tweets.js archive export) and some [browser automation](https://github.com/telezoic/thread-keeper-automator) to build a complete set of tweets as pdfs from our Library's twitter account. Other university accounts are pending . . . 

We really appreciate the tool your team built. :)

**Comment by matteocargnelutti** [comment]
@telezoic Awesome! I'm really glad thread-keeper is proving helpful 😄 . 

I had a look at `thread-keeper-automator`, which is super interesting. 

I have a quick question / observation regarding the last step you recommend in your docs:
```
9. Combine the pdfs. I used Ghostscript here.

gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=COMBINEDPDFS.pdf *.pdf
```

**I've had issues with Ghostscript when working on thread-keeper:** 
On Linux specifically, it was removing all attachments and sometimes breaking the signature. 
Is it something you've observed as well? It makes sense for the signatures to be gone _(and you might want to sign the combined PDF)_, but it might be good to keep the attachments. More generally, I wonder if attachments of multiple documents can be combined? 

Cheers.

**Comment by telezoic** [comment]
thanks @matteocargnelutti 

You're right, of course. I have yet to find a tool that will preserve attachments when I combine the files. Ghostscript removes them, as does pdfunite, and even automator on my local machine. I'm going to keep investigating this. I'm signing the combined doc with this handy tool - https://github.com/open-pdf-sign/open-pdf-sign

Thanks again, 

D.
